"""fix_tables

Revision ID: 0a1e0eb9872f
Revises: 46f24a55c69e
Create Date: 2026-05-04 02:04:56.918432

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0a1e0eb9872f'
down_revision: Union[str, Sequence[str], None] = '46f24a55c69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('classification_pure_id', sa.BIGINT(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('term_ru', sa.String(), nullable=True),
    sa.Column('term_en', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('classification_scheme_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['classification_scheme_id'], ['classification_schemes.classification_scheme_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classification_pure_id')
    )
    op.create_table('persons_organisational_units_staff_associations',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('organisational_unit_id', sa.Uuid(), nullable=False),
    sa.Column('period', postgresql.TSTZRANGE(), nullable=True),
    sa.ForeignKeyConstraint(['organisational_unit_id'], ['organisational_units.organisational_unit_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('person_id', 'organisational_unit_id')
    )
    op.create_table('persons_organisational_units_student_associations',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('organisational_unit_id', sa.Uuid(), nullable=False),
    sa.Column('period', postgresql.TSTZRANGE(), nullable=True),
    sa.ForeignKeyConstraint(['organisational_unit_id'], ['organisational_units.organisational_unit_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('person_id', 'organisational_unit_id')
    )
    op.drop_table('persons_organisational_units_student_association')
    op.drop_table('classification')
    op.drop_table('persons_organisational_units_staff_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons_organisational_units_staff_association',
    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisational_unit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period', postgresql.TSTZRANGE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisational_unit_id'], ['organisational_units.organisational_unit_id'], name=op.f('persons_organisational_units_staff__organisational_unit_id_fkey')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], name=op.f('persons_organisational_units_staff_association_person_id_fkey')),
    sa.PrimaryKeyConstraint('person_id', 'organisational_unit_id', name=op.f('persons_organisational_units_staff_association_pkey'))
    )
    op.create_table('classification',
    sa.Column('classification_pure_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uri', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('term_ru', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('term_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('classification_scheme_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['classification_scheme_id'], ['classification_schemes.classification_scheme_id'], name=op.f('classification_classification_scheme_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classification_pure_id', name=op.f('classification_pkey'))
    )
    op.create_table('persons_organisational_units_student_association',
    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisational_unit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period', postgresql.TSTZRANGE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisational_unit_id'], ['organisational_units.organisational_unit_id'], name=op.f('persons_organisational_units_studen_organisational_unit_id_fkey')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], name=op.f('persons_organisational_units_student_association_person_id_fkey')),
    sa.PrimaryKeyConstraint('person_id', 'organisational_unit_id', name=op.f('persons_organisational_units_student_association_pkey'))
    )
    op.drop_table('persons_organisational_units_student_associations')
    op.drop_table('persons_organisational_units_staff_associations')
    op.drop_table('classifications')
    # ### end Alembic commands ###
