"""add_essential_pure_objects

Revision ID: 46f24a55c69e
Revises: 835502806da0
Create Date: 2026-04-26 21:47:06.811050

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '46f24a55c69e'
down_revision: Union[str, Sequence[str], None] = '835502806da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_schemes',
    sa.Column('classification_scheme_id', sa.Uuid(), nullable=False),
    sa.Column('pure_id', sa.BIGINT(), nullable=False),
    sa.Column('base_uri', sa.String(), nullable=False),
    sa.Column('description_ru', sa.String(), nullable=True),
    sa.Column('description_en', sa.String(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('classification_scheme_id'),
    sa.UniqueConstraint('pure_id')
    )
    op.create_table('organisational_units',
    sa.Column('organisational_unit_id', sa.Uuid(), nullable=False),
    sa.Column('pure_id', sa.BIGINT(), nullable=False),
    sa.Column('type_id', sa.BIGINT(), nullable=True),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('parents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('organisational_unit_id'),
    sa.UniqueConstraint('pure_id')
    )
    op.create_table('research_outputs',
    sa.Column('research_output_id', sa.Uuid(), nullable=False),
    sa.Column('pure_id', sa.BIGINT(), nullable=False),
    sa.Column('type_id', sa.BIGINT(), nullable=True),
    sa.Column('category_type_id', sa.BIGINT(), nullable=True),
    sa.Column('language_type_id', sa.BIGINT(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('research_output_id'),
    sa.UniqueConstraint('pure_id')
    )
    op.create_table('classification',
    sa.Column('classification_pure_id', sa.BIGINT(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('term_ru', sa.String(), nullable=True),
    sa.Column('term_en', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('classification_scheme_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['classification_scheme_id'], ['classification_schemes.classification_scheme_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classification_pure_id')
    )
    op.create_table('persons_organisational_units_staff_association',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('organisational_unit_id', sa.Uuid(), nullable=False),
    sa.Column('period', postgresql.TSTZRANGE(), nullable=True),
    sa.ForeignKeyConstraint(['organisational_unit_id'], ['organisational_units.organisational_unit_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('person_id', 'organisational_unit_id')
    )
    op.create_table('persons_organisational_units_student_association',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('organisational_unit_id', sa.Uuid(), nullable=False),
    sa.Column('period', postgresql.TSTZRANGE(), nullable=True),
    sa.ForeignKeyConstraint(['organisational_unit_id'], ['organisational_units.organisational_unit_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('person_id', 'organisational_unit_id')
    )
    op.add_column('persons', sa.Column('pure_id', sa.BIGINT(), nullable=False))
    op.add_column('persons', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('persons', sa.Column('ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('persons', sa.Column('orcid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'persons', ['pure_id'])
    op.drop_column('persons', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'persons', type_='unique')
    op.drop_column('persons', 'orcid')
    op.drop_column('persons', 'ids')
    op.drop_column('persons', 'titles')
    op.drop_column('persons', 'last_name')
    op.drop_column('persons', 'first_name')
    op.drop_column('persons', 'pure_id')
    op.drop_table('persons_organisational_units_student_association')
    op.drop_table('persons_organisational_units_staff_association')
    op.drop_table('classification')
    op.drop_table('research_outputs')
    op.drop_table('organisational_units')
    op.drop_table('classification_schemes')
    # ### end Alembic commands ###
