"""init

Revision ID: 7a359653c9e7
Revises:
Create Date: 2026-05-22 14:39:17.296363

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a359653c9e7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classification_schemes",
        sa.Column("classification_scheme_id", sa.Uuid(), nullable=False),
        sa.Column("pure_id", sa.BIGINT(), nullable=False),
        sa.Column("base_uri", sa.String(), nullable=False),
        sa.Column("description_ru", sa.String(), nullable=True),
        sa.Column("description_en", sa.String(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("classification_scheme_id"),
        sa.UniqueConstraint("pure_id"),
    )
    op.create_table(
        "organisational_units",
        sa.Column("organisational_unit_id", sa.Uuid(), nullable=False),
        sa.Column("pure_id", sa.BIGINT(), nullable=False),
        sa.Column("type_id", sa.BIGINT(), nullable=True),
        sa.Column("name_ru", sa.String(), nullable=True),
        sa.Column("name_en", sa.String(), nullable=True),
        sa.Column("parents", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("organisational_unit_id"),
        sa.UniqueConstraint("pure_id"),
    )
    op.create_table(
        "persons",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("pure_id", sa.BIGINT(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("titles", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("orcid", sa.String(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("person_id"),
        sa.UniqueConstraint("pure_id"),
    )
    op.create_table(
        "research_outputs",
        sa.Column("research_output_id", sa.Uuid(), nullable=False),
        sa.Column("pure_id", sa.BIGINT(), nullable=False),
        sa.Column("type_id", sa.BIGINT(), nullable=True),
        sa.Column("category_type_id", sa.BIGINT(), nullable=True),
        sa.Column("language_type_id", sa.BIGINT(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("publication_statuses", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("research_output_id"),
        sa.UniqueConstraint("pure_id"),
    )
    op.create_table(
        "classifications",
        sa.Column("classification_pure_id", sa.BIGINT(), nullable=False),
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("term_ru", sa.String(), nullable=True),
        sa.Column("term_en", sa.String(), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("classification_scheme_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classification_scheme_id"],
            ["classification_schemes.classification_scheme_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("classification_pure_id"),
    )
    op.create_index(
        op.f("ix_classifications_classification_scheme_id"),
        "classifications",
        ["classification_scheme_id"],
        unique=False,
    )
    op.create_table(
        "persons_organisational_units_staff_associations",
        sa.Column("pure_id", sa.BIGINT(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("organisational_unit_id", sa.Uuid(), nullable=False),
        sa.Column("period", postgresql.TSTZRANGE(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisational_unit_id"],
            ["organisational_units.organisational_unit_id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.person_id"],
        ),
        sa.PrimaryKeyConstraint("pure_id"),
    )
    op.create_index(
        op.f("ix_persons_organisational_units_staff_associations_organisational_unit_id"),
        "persons_organisational_units_staff_associations",
        ["organisational_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persons_organisational_units_staff_associations_person_id"),
        "persons_organisational_units_staff_associations",
        ["person_id"],
        unique=False,
    )
    op.create_table(
        "persons_organisational_units_student_associations",
        sa.Column("pure_id", sa.BIGINT(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("organisational_unit_id", sa.Uuid(), nullable=False),
        sa.Column("period", postgresql.TSTZRANGE(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisational_unit_id"],
            ["organisational_units.organisational_unit_id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.person_id"],
        ),
        sa.PrimaryKeyConstraint("pure_id"),
    )
    op.create_index(
        op.f("ix_persons_organisational_units_student_associations_organisational_unit_id"),
        "persons_organisational_units_student_associations",
        ["organisational_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persons_organisational_units_student_associations_person_id"),
        "persons_organisational_units_student_associations",
        ["person_id"],
        unique=False,
    )
    op.create_table(
        "research_outputs_organisational_units_associations",
        sa.Column("research_output_id", sa.Uuid(), nullable=False),
        sa.Column("organisational_unit_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisational_unit_id"],
            ["organisational_units.organisational_unit_id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_output_id"],
            ["research_outputs.research_output_id"],
        ),
        sa.PrimaryKeyConstraint("research_output_id", "organisational_unit_id"),
    )
    op.create_index(
        op.f("ix_research_outputs_organisational_units_associations_organisational_unit_id"),
        "research_outputs_organisational_units_associations",
        ["organisational_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_outputs_organisational_units_associations_research_output_id"),
        "research_outputs_organisational_units_associations",
        ["research_output_id"],
        unique=False,
    )
    op.create_table(
        "research_outputs_persons_associations",
        sa.Column("research_output_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("pure_id", sa.BIGINT(), nullable=False),
        sa.Column("person_role_type_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.person_id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_output_id"],
            ["research_outputs.research_output_id"],
        ),
        sa.PrimaryKeyConstraint("research_output_id", "person_id"),
        sa.UniqueConstraint("pure_id"),
    )
    op.create_index(
        op.f("ix_research_outputs_persons_associations_person_id"),
        "research_outputs_persons_associations",
        ["person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_outputs_persons_associations_research_output_id"),
        "research_outputs_persons_associations",
        ["research_output_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_research_outputs_persons_associations_research_output_id"),
        table_name="research_outputs_persons_associations",
    )
    op.drop_index(
        op.f("ix_research_outputs_persons_associations_person_id"), table_name="research_outputs_persons_associations"
    )
    op.drop_table("research_outputs_persons_associations")
    op.drop_index(
        op.f("ix_research_outputs_organisational_units_associations_research_output_id"),
        table_name="research_outputs_organisational_units_associations",
    )
    op.drop_index(
        op.f("ix_research_outputs_organisational_units_associations_organisational_unit_id"),
        table_name="research_outputs_organisational_units_associations",
    )
    op.drop_table("research_outputs_organisational_units_associations")
    op.drop_index(
        op.f("ix_persons_organisational_units_student_associations_person_id"),
        table_name="persons_organisational_units_student_associations",
    )
    op.drop_index(
        op.f("ix_persons_organisational_units_student_associations_organisational_unit_id"),
        table_name="persons_organisational_units_student_associations",
    )
    op.drop_table("persons_organisational_units_student_associations")
    op.drop_index(
        op.f("ix_persons_organisational_units_staff_associations_person_id"),
        table_name="persons_organisational_units_staff_associations",
    )
    op.drop_index(
        op.f("ix_persons_organisational_units_staff_associations_organisational_unit_id"),
        table_name="persons_organisational_units_staff_associations",
    )
    op.drop_table("persons_organisational_units_staff_associations")
    op.drop_index(op.f("ix_classifications_classification_scheme_id"), table_name="classifications")
    op.drop_table("classifications")
    op.drop_table("research_outputs")
    op.drop_table("persons")
    op.drop_table("organisational_units")
    op.drop_table("classification_schemes")
    # ### end Alembic commands ###
