"""research_outputs_links

Revision ID: 8f9050e6298b
Revises: 0a1e0eb9872f
Create Date: 2026-05-09 14:53:37.864070

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f9050e6298b"
down_revision: str | Sequence[str] | None = "0a1e0eb9872f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_outputs_organisational_units_associations",
        sa.Column("research_output_id", sa.Uuid(), nullable=False),
        sa.Column("organisational_unit_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisational_unit_id"],
            ["organisational_units.organisational_unit_id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_output_id"],
            ["research_outputs.research_output_id"],
        ),
        sa.PrimaryKeyConstraint("research_output_id", "organisational_unit_id"),
    )
    op.create_table(
        "research_outputs_persons_associations",
        sa.Column("research_output_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("pure_id", sa.BIGINT(), nullable=False),
        sa.Column("person_role_type_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.person_id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_output_id"],
            ["research_outputs.research_output_id"],
        ),
        sa.PrimaryKeyConstraint("research_output_id", "person_id"),
        sa.UniqueConstraint("pure_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("research_outputs_persons_associations")
    op.drop_table("research_outputs_organisational_units_associations")
    # ### end Alembic commands ###
