export POSTGRES_DB := "pure_db"
export POSTGRES_HOST := "localhost"
export POSTGRES_PORT := "5432"
export POSTGRES_USER := "pure_db_user"
export PGPASSWORD := "password"

set quiet := true

# Lists available commands
default:
    just --list

# Run tests
test:
    uv run pytest -v

# Starts jupyter lab
jupyter:
    uv run jupyter lab --ip 0.0.0.0

# Starts HTTP server
serve:
    uv run app

# Run dash app (UI)
dash:
    uv run src/app/client.py

# Migrate postgres database using alembic
pg-migrate:
    uv run alembic upgrade head

migrate: pg-migrate

# Starts development database in a podman container
pg-up: pg-start

# Starts development database in a podman container
pg-start:
    podman run \
        --name pure-postgres \
        -p $POSTGRES_PORT:5432 \
        -e POSTGRES_DB=$POSTGRES_DB \
        -e POSTGRES_USER=$POSTGRES_USER \
        -e POSTGRES_PASSWORD=$PGPASSWORD \
        -d \
        docker.io/postgres:18

# Stops database and removes container (erases all data)
pg-down:
    -podman stop pure-postgres
    -podman rm pure-postgres

# Wait for postgres to start
pg-wait:
    #!/usr/bin/env sh
    until psql -w -h $POSTGRES_HOST -p $POSTGRES_PORT $POSTGRES_DB $POSTGRES_USER -c 'SELECT 1;'
    do
        echo "Waiting for postgres"
        sleep 1
    done
    echo "Postgres is up"

# Connect to postgres database with psql
pg-connect:
    psql -w -h $POSTGRES_HOST -p $POSTGRES_PORT $POSTGRES_DB $POSTGRES_USER

# Pull postgres image
pg-pull:
    podman pull docker.io/postgres:18

format: fmt

# Format code
fmt:
    uv run isort -m 3 --tc .

load-all-persons:
    curl -X 'POST' 'http://localhost:8000/load/persons' -H 'accept: application/json' -H 'Content-Type: application/json' -d @data/persons.json && echo
load-all-research-outputs:
    curl -X 'POST' 'http://localhost:8000/load/research-outputs' -H 'accept: application/json' -H 'Content-Type: application/json' -d @data/research-outputs.json && echo
load-all-organisational-units:
    curl -X 'POST' 'http://localhost:8000/load/organisational-units' -H 'accept: application/json' -H 'Content-Type: application/json' -d @data/organisational-units.json && echo
load-all-classification-schemes:
    curl -X 'POST' 'http://localhost:8000/load/classification-schemes' -H 'accept: application/json' -H 'Content-Type: application/json' -d @data/classification-schemes.json && echo
