[project]
name = "experiments"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.4.3",
    "pandas>=3.0.1",
    "polars>=1.39.2",
]

[tool.uv.workspace]
members = [
    "explore-persons-organisations",
    "explore-research-outputs",
    "recommend-research-partners",
]
